### ISSUE TITLE
Could not find method

### ISSUE THREAD

**Issue by fsickle** [dialdroid-android/ic3-dialdroid#5]
Exception in thread "main" java.lang.RuntimeException: Could not find method
	at soot.jimple.infoflow.android.callbacks.AbstractCallbackAnalyzer.getMethodFromHierarchyEx(AbstractCallbackAnalyzer.java:341)
	at soot.jimple.infoflow.android.callbacks.AbstractCallbackAnalyzer.getMethodFromHierarchyEx(AbstractCallbackAnalyzer.java:340)
	at soot.jimple.infoflow.android.callbacks.AbstractCallbackAnalyzer.analyzeClassInterfaceCallbacks(AbstractCallbackAnalyzer.java:365)
	at soot.jimple.infoflow.android.callbacks.AbstractCallbackAnalyzer.analyzeClass(AbstractCallbackAnalyzer.java:296)
	at soot.jimple.infoflow.android.callbacks.AbstractCallbackAnalyzer.analyzeMethodForCallbackRegistrations(AbstractCallbackAnalyzer.java:194)
	at soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer.analyzeRechableMethods(DefaultCallbackAnalyzer.java:131)
	at soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer.access$100(DefaultCallbackAnalyzer.java:40)
	at soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer$1.internalTransform(DefaultCallbackAnalyzer.java:84)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.ScenePack.internalApply(ScenePack.java:40)
	at soot.Pack.apply(Pack.java:118)
	at edu.psu.cse.siis.ic3.SetupApplication.calculateCallbackMethods(SetupApplication.java:135)
	at edu.psu.cse.siis.ic3.SetupApplication.calculateSourcesSinksEntrypoints(SetupApplication.java:258)
	at edu.psu.cse.siis.ic3.Ic3Analysis.initializeAnalysis(Ic3Analysis.java:162)
	at edu.psu.cse.siis.ic3.Ic3Analysis.initializeAnalysis(Ic3Analysis.java:66)
	at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:69)
	at edu.psu.cse.siis.ic3.Main.main(Main.java:37)

There is something wrong when running ic3, how to fix it ?

**Comment by TDklm** [comment]
Have you soved this problem? I have meet this  too, Maybe it's  about the android verson.

**Comment by fsickle** [comment]
> Have you soved this problem? I have meet this too, Maybe it's about the android verson.

sorry，I already lost my notes……
